FROM apache/airflow:2.9.2-python3.12

USER root

# dependencias minimas para o Airflow + DockerOperator
RUN apt-get update && apt-get install -y --no-install-recommends \
    docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# apenas o provider do Docker para o DockerOperator
RUN pip install --no-cache-dir apache-airflow-providers-docker==3.9.0